TankGame: DiffCard Class Reference
DiffCard Class Reference abstract
#include "diffcard.h"
Public Member Functions
DiffCard (QObject *parent=0)
virtual void loadFromList (QList< DiffElement *> &newItems)
virtual void loadFromList (QList< DiffElement *> *newItems)
virtual int getCountOfDiff ()=0
virtual DiffElement * at (int i)=0
virtual DiffCard * subdiffForElements (QList< IBaseGameElement *> items)=0
virtual void append (DiffElement *diff)=0
virtual void clear ()=0
virtual void updateFromOtherCard (DiffCard *card)=0
virtual void freeItems ()
freeItems simular to claer but also call destructor for diff elemenst
Detailed Description
Definition at line 9 of file diffcard.h.
Constructor & Destructor Documentation
DiffCard()
DiffCard::DiffCard (QObject * parent = 0) explicit
Definition at line 3 of file diffcard.cpp.
 : QObject(parent) {}
Member Function Documentation
append()
virtual void DiffCard::append (DiffElement * diff) pure virtual
Implemented in SimpleDiffCard.
at()
virtual DiffElement* DiffCard::at (int i) pure virtual
Implemented in SimpleDiffCard.
Referenced by ListBseMap::updateFromDiff().
clear()
virtual void DiffCard::clear () pure virtual
Implemented in SimpleDiffCard.
freeItems()
void DiffCard::freeItems () virtual
freeItems simular to claer but also call destructor for diff elemenst
Definition at line 14 of file diffcard.cpp.
{
   for (int i = 0; i < getCountOfDiff(); i++) {
     delete at(i);
   }
   clear();
 }
getCountOfDiff()
virtual int DiffCard::getCountOfDiff () pure virtual
Implemented in SimpleDiffCard.
Referenced by ListBseMap::updateFromDiff().
loadFromList() [1/2]
void DiffCard::loadFromList (QList< DiffElement *> & newItems) virtual
Definition at line 5 of file diffcard.cpp.
{
   foreach (auto i, newItems) { append(i); }
 }
loadFromList() [2/2]
void DiffCard::loadFromList (QList< DiffElement *> * newItems) virtual
Definition at line 9 of file diffcard.cpp.
Referenced by MainGameLoop::getAllMapAsDiff().
{
   for (int i = 0; i < newItems->size(); i++)
     append(newItems->at(i));
 }
subdiffForElements()
virtual DiffCard* DiffCard::subdiffForElements (QList< IBaseGameElement *> items) pure virtual
Implemented in SimpleDiffCard.
updateFromOtherCard()
virtual void DiffCard::updateFromOtherCard (DiffCard * card) pure virtual
Implemented in SimpleDiffCard.