TankGame: InfinityDouble Class Reference
InfinityDouble Class Reference
#include "infinitydouble.h"
Public Member Functions
InfinityDouble (InfinityDouble &id)
Static Public Member Functions
static InfinityDouble * FromValue (double w)
static InfinityDouble * InfinityValue ()
Friends
QDataStream & operator<< (QDataStream &stream, const InfinityDouble &myclass)
QDataStream & operator>> (QDataStream &stream, InfinityDouble &myclass)
Detailed Description
Definition at line 6 of file infinitydouble.h.
Constructor & Destructor Documentation
InfinityDouble()
InfinityDouble::InfinityDouble (InfinityDouble & id)
Definition at line 3 of file infinitydouble.cpp.
Referenced by FromValue(), MapIniter::getRandomGrass(), and InfinityValue().
{
   this->w = id.w;
   this->isInfinity = id.isInfinity;
 }
Member Function Documentation
FromValue()
InfinityDouble * InfinityDouble::FromValue (double w) static
Definition at line 10 of file infinitydouble.cpp.
References InfinityDouble().
Referenced by MapIniter::getRandomGrass().
{
   InfinityDouble* result = new InfinityDouble();
   result->w = w;
   result->isInfinity = false;
   return result;
 }
InfinityValue()
InfinityDouble * InfinityDouble::InfinityValue () static
Definition at line 17 of file infinitydouble.cpp.
References InfinityDouble().
Referenced by MapIniter::getRandomGrass().
{
   InfinityDouble* result = new InfinityDouble();
   result->isInfinity = true;
   return result;
 }
Friends And Related Function Documentation
operator<<
QDataStream& operator<< (QDataStream & stream, const InfinityDouble & myclass) friend
Definition at line 9 of file infinitydouble.h.
{
     return stream << myclass.isInfinity << myclass.w;
   }
operator>>
QDataStream& operator>> (QDataStream & stream, InfinityDouble & myclass) friend
Definition at line 14 of file infinitydouble.h.
{
     return stream >> myclass.isInfinity >> myclass.w;
   }