TankGame: BaseTank Class Reference
BaseTank Class Reference
#include "basetank.h"
Public Member Functions
BaseTank ()
BaseTank (GameElementData &data)
virtual void setType (int value) override
virtual BaseBulet generateBullet () const
virtual void setAdditionakData (QByteArray *data) override
virtual QByteArray * getAdditionalData () const
virtual void setDirection (double _direction)
virtual double getDirection () const
virtual void setSpeed (double _speed)
virtual double getSpeed () const
virtual void nextStep ()
virtual QVector3D * getPosition () const
virtual int getType () const
virtual InfinityDouble * getHelth () const
virtual InfinityDouble * getWeight () const
virtual InfinityDouble * getMaxTransitWeight () const
virtual QString getName () const
virtual int getRVision () const
virtual void setPosition (QVector3D *value)
virtual void setHelth (InfinityDouble *value)
virtual void setWeight (InfinityDouble *value)
virtual void setTransitWeight (InfinityDouble *value)
virtual void setName (QString name)
virtual void setRVision (int _rVison)
void copyData (GameElementData &out)
Protected Member Functions
virtual void init (GameElementData &data)
Protected Attributes
double direction = 0
double speed = 0
int fireType = 0
fireType 0 for non fire -1 for single fire if fireType > 0 then fire will be call evry fireType tik of game
QVector3D * position = nullptr
InfinityDouble * helth = nullptr
InfinityDouble * weight = nullptr
InfinityDouble * transitWeight = nullptr
QByteArray * additionalData = nullptr
int rVision = 1
int type = -1
QString name
Detailed Description
Definition at line 6 of file basetank.h.
Constructor & Destructor Documentation
BaseTank() [1/2]
BaseTank::BaseTank ()
Definition at line 4 of file basetank.cpp.
References eSimpleTank, IBaseGameElement::nextStep(), and IBaseGameElement::type.
                    : IBaseGameElement() {
   this->type = eSimpleTank;
 }
BaseTank() [2/2]
BaseTank::BaseTank (GameElementData & data)
Definition at line 8 of file basetank.cpp.
References eSimpleTank, IBaseGameElement::nextStep(), and IBaseGameElement::type.
                                         : IBaseGameElement() {
   init(data);
   this->type = eSimpleTank;
 }
Member Function Documentation
copyData()
void IBaseGameElement::copyData (GameElementData & out) inherited
Definition at line 27 of file ibasegameelement.cpp.
Referenced by DiffElement::DiffElement().
{
   out.position = new QVector3D(*position);
   out.helth = new InfinityDouble(*helth);
   out.weight = new InfinityDouble(*weight);
   out.transitWeight = new InfinityDouble(*transitWeight);
   if (additionalData == nullptr)
     out.additionalData = nullptr;
   else
     out.additionalData = new QByteArray(*additionalData);
   out.type = type;
   out.name = name;
   out.rVision = rVision;
 }
generateBullet()
BaseBulet BaseTank::generateBullet () const virtual
Definition at line 20 of file basetank.cpp.
 {}
getAdditionalData()
QByteArray * BaseTank::getAdditionalData () const virtual
Reimplemented from IBaseGameElement.
Definition at line 28 of file basetank.cpp.
{
   this->additionalData->clear();
   QDataStream stream(this->additionalData, QIODevice::WriteOnly);
   stream << direction << speed << fireType;
   return additionalData;
 }
getDirection()
virtual double BaseTank::getDirection () const inline virtual
Definition at line 21 of file basetank.h.
References direction.
 { return direction; }
getHelth()
virtual InfinityDouble* IBaseGameElement::getHelth () const inline virtual inherited
Definition at line 64 of file ibasegameelement.h.
 { return helth; }
getMaxTransitWeight()
virtual InfinityDouble* IBaseGameElement::getMaxTransitWeight () const inline virtual inherited
Definition at line 66 of file ibasegameelement.h.
 { return transitWeight; }
getName()
virtual QString IBaseGameElement::getName () const inline virtual inherited
Definition at line 67 of file ibasegameelement.h.
 { return name; }
getPosition()
virtual QVector3D* IBaseGameElement::getPosition () const inline virtual inherited
Definition at line 62 of file ibasegameelement.h.
 { return position; }
getRVision()
virtual int IBaseGameElement::getRVision () const inline virtual inherited
Definition at line 69 of file ibasegameelement.h.
References IBaseGameElement::rVision.
 { return rVision; }
getSpeed()
virtual double BaseTank::getSpeed () const inline virtual
Definition at line 24 of file basetank.h.
References speed.
 { return speed; }
getType()
virtual int IBaseGameElement::getType () const inline virtual inherited
Definition at line 63 of file ibasegameelement.h.
References IBaseGameElement::type.
 { return type; }
getWeight()
virtual InfinityDouble* IBaseGameElement::getWeight () const inline virtual inherited
Definition at line 65 of file ibasegameelement.h.
 { return weight; }
init()
void IBaseGameElement::init (GameElementData & data) protected virtual inherited
Definition at line 41 of file ibasegameelement.cpp.
{
   setHelth(new InfinityDouble(*data.helth));
   setWeight(new InfinityDouble(*data.weight));
   setTransitWeight(new InfinityDouble(*data.transitWeight));
   setPosition(new QVector3D(*data.position));
   setName(data.name);
   setAdditionakData(new QByteArray(*data.additionalData));
   setRVision(data.rVision);
   setType(data.type);
 }
nextStep()
virtual void IBaseGameElement::nextStep () inline virtual inherited
Definition at line 60 of file ibasegameelement.h.
Referenced by BaseBasis::BaseBasis(), BaseBulet::BaseBulet(), BaseTank(), MapIniter::getRandomGrass(), IBaseGameElement::IBaseGameElement(), MapIniter::initSimapleMap(), and ListBseMap::proccessAllInR().
 {};
setAdditionakData()
void BaseTank::setAdditionakData (QByteArray * data) override virtual
Reimplemented from IBaseGameElement.
Definition at line 22 of file basetank.cpp.
{
   IBaseGameElement::setAdditionakData(data);
   QDataStream stream(*data);
   stream >> direction >> speed >> fireType;
 }
setDirection()
void BaseTank::setDirection (double _direction) virtual
Definition at line 35 of file basetank.cpp.
References direction.
{
   direction = _direction;
   getAdditionalData();
 }
setHelth()
virtual void IBaseGameElement::setHelth (InfinityDouble * value) inline virtual inherited
Definition at line 87 of file ibasegameelement.h.
Referenced by MapIniter::getRandomGrass().
 { this->helth = value; }
setName()
virtual void IBaseGameElement::setName (QString name) inline virtual inherited
Definition at line 93 of file ibasegameelement.h.
 { this->name = name; }
setPosition()
virtual void IBaseGameElement::setPosition (QVector3D * value) inline virtual inherited
Definition at line 86 of file ibasegameelement.h.
 { this->position = value; }
setRVision()
virtual void IBaseGameElement::setRVision (int _rVison) inline virtual inherited
Definition at line 97 of file ibasegameelement.h.
References IBaseGameElement::rVision.
 { rVision = _rVison; }
setSpeed()
void BaseTank::setSpeed (double _speed) virtual
Definition at line 40 of file basetank.cpp.
References speed.
{
   speed = _speed;
   getAdditionalData();
 }
setTransitWeight()
virtual void IBaseGameElement::setTransitWeight (InfinityDouble * value) inline virtual inherited
Definition at line 89 of file ibasegameelement.h.
Referenced by MapIniter::getRandomGrass().
{
     this->transitWeight = value;
   }
setType()
void BaseTank::setType (int value) override virtual
Reimplemented from IBaseGameElement.
Definition at line 13 of file basetank.cpp.
References eSimpleTank.
{
   if (value != ((int)eSimpleTank)) {
     Q_ASSERT_X(false, "game logic", "Wrong type for tank");
   }
   IBaseGameElement::setType(value);
 }
setWeight()
virtual void IBaseGameElement::setWeight (InfinityDouble * value) inline virtual inherited
Definition at line 88 of file ibasegameelement.h.
 { this->weight = value; }
Member Data Documentation
additionalData
QByteArray* IBaseGameElement::additionalData = nullptr protected inherited
Definition at line 109 of file ibasegameelement.h.
direction
double BaseTank::direction = 0 protected
Definition at line 27 of file basetank.h.
Referenced by getDirection(), and setDirection().
fireType
int BaseTank::fireType = 0 protected
fireType 0 for non fire -1 for single fire if fireType > 0 then fire will be call evry fireType tik of game
Definition at line 35 of file basetank.h.
helth
InfinityDouble* IBaseGameElement::helth = nullptr protected inherited
Definition at line 106 of file ibasegameelement.h.
name
QString IBaseGameElement::name protected inherited
Definition at line 113 of file ibasegameelement.h.
position
QVector3D* IBaseGameElement::position = nullptr protected inherited
Definition at line 105 of file ibasegameelement.h.
rVision
int IBaseGameElement::rVision = 1 protected inherited
Definition at line 110 of file ibasegameelement.h.
Referenced by IBaseGameElement::getRVision(), and IBaseGameElement::setRVision().
speed
double BaseTank::speed = 0 protected
Definition at line 28 of file basetank.h.
Referenced by getSpeed(), and setSpeed().
transitWeight
InfinityDouble* IBaseGameElement::transitWeight = nullptr protected inherited
Definition at line 108 of file ibasegameelement.h.
type
int IBaseGameElement::type = -1 protected inherited
Definition at line 112 of file ibasegameelement.h.
Referenced by BaseBasis::BaseBasis(), BaseBulet::BaseBulet(), BaseTank(), IBaseGameElement::getType(), and IBaseGameElement::setType().
weight
InfinityDouble* IBaseGameElement::weight = nullptr protected inherited
Definition at line 107 of file ibasegameelement.h.