TankGame: DiffElement Class Reference
DiffElement Class Reference
#include "diffelement.h"
Public Member Functions
~DiffElement ()
DiffElement ()
DiffElement (DiffElement &element)
DiffElement (eDiffType type, IBaseGameElement *data)
GameElementData * getData ()
IBaseGameElement * generateGameElementInstance ()
void update (DiffElement *element)
Public Attributes
eDiffType type
uint64_t time
Protected Attributes
GameElementData * data
Friends
QDataStream & operator<< (QDataStream &stream, const DiffElement &myclass)
QDataStream & operator>> (QDataStream &stream, DiffElement &myclass)
Detailed Description
Definition at line 10 of file diffelement.h.
Constructor & Destructor Documentation
~DiffElement()
DiffElement::~DiffElement ()
Definition at line 3 of file diffelement.cpp.
References data.
{
   delete data;
 }
DiffElement() [1/3]
DiffElement::DiffElement ()
Definition at line 7 of file diffelement.cpp.
References data, eEmpty, and type.
{
   data = new GameElementData();
   type = eEmpty;
   time = 0;
 }
DiffElement() [2/3]
DiffElement::DiffElement (DiffElement & element)
Definition at line 13 of file diffelement.cpp.
References data, eEmpty, type, and update().
{
   data = new GameElementData();
   type = eEmpty;
   time = 0;
   this->update(&element);
 }
DiffElement() [3/3]
DiffElement::DiffElement (eDiffType type, IBaseGameElement * data)
Definition at line 20 of file diffelement.cpp.
References IBaseGameElement::copyData(), data, and type.
{
   this->type = type;
   this->data = new GameElementData();
   data->copyData(*this->data);
   time = 0;
 }
Member Function Documentation
generateGameElementInstance()
IBaseGameElement * DiffElement::generateGameElementInstance ()
Definition at line 27 of file diffelement.cpp.
References data, and getElement().
Referenced by ListBseMap::updateFromDiff().
{
   return getElement(*data);
 }
getData()
GameElementData* DiffElement::getData () inline
Definition at line 31 of file diffelement.h.
References data.
 { return data; }
update()
void DiffElement::update (DiffElement * element)
Definition at line 31 of file diffelement.cpp.
References type.
Referenced by DiffElement().
{
   this->type = element->type;
   this->time = element->time;
   this->data->position = new QVector3D(*element->getData()->position);
   this->data->helth = new InfinityDouble(*element->getData()->helth);
   this->data->weight = new InfinityDouble(*element->getData()->weight);
   this->data->transitWeight =
       new InfinityDouble(*element->getData()->transitWeight);
   this->data->additionalData =
       new QByteArray(*element->getData()->additionalData);
   this->data->type = element->getData()->type;
   this->data->name = element->getData()->name;
   this->data->rVision = element->getData()->rVision;
 }
Friends And Related Function Documentation
operator<<
QDataStream& operator<< (QDataStream & stream, const DiffElement & myclass) friend
Definition at line 16 of file diffelement.h.
{
     stream << ((int)myclass.type);
     return stream << (*myclass.data);
   }
operator>>
QDataStream& operator>> (QDataStream & stream, DiffElement & myclass) friend
Definition at line 21 of file diffelement.h.
{
     int type;
     myclass.data->defaultInit();
     stream >> type >> (*myclass.data);
     myclass.type = (eDiffType)type;
     return stream;
   }
Member Data Documentation
data
GameElementData* DiffElement::data protected
Definition at line 37 of file diffelement.h.
Referenced by DiffElement(), generateGameElementInstance(), getData(), and ~DiffElement().
time
uint64_t DiffElement::time
Definition at line 29 of file diffelement.h.
type
eDiffType DiffElement::type
Definition at line 28 of file diffelement.h.
Referenced by DiffElement(), update(), and ListBseMap::updateFromDiff().