TankGame: ServerConnection Class Reference
ServerConnection Class Reference
#include "serverconnection.h"
Signals
void onServerError (serverError error)
Public Member Functions
~ServerConnection ()
void startServer ()
void receiveResponce (DiffCard *diff, MessageForServer *message)
virtual void setDefaultReceiver (MailReceiver *receiver)
Static Public Member Functions
static ServerConnection * getServerInstance ()
Protected Slots
void onWorkerStop (ServerWorker *worker)
Protected Member Functions
ServerConnection ()
void run ()
Protected Attributes
QTcpServer * server
QList< ServerWorker * > * connections
MailReceiver * receiver
Static Protected Attributes
static ServerConnection * instance = nullptr
Detailed Description
Definition at line 12 of file serverconnection.h.
Constructor & Destructor Documentation
~ServerConnection()
ServerConnection::~ServerConnection ()
Definition at line 6 of file serverconnection.cpp.
{
   for (int i = 0; i < connections->size(); i++)
     delete connections->at(i);
   delete connections;
 }
ServerConnection()
ServerConnection::ServerConnection () protected
Definition at line 12 of file serverconnection.cpp.
{
   connections = new QList<ServerWorker*>();
 }
Member Function Documentation
getServerInstance()
static ServerConnection* ServerConnection::getServerInstance () inline static
Definition at line 18 of file serverconnection.h.
References instance.
Referenced by initServer().
{
     if (instance == nullptr)
       instance = new ServerConnection();
     return instance;
   }
onServerError
void ServerConnection::onServerError (serverError error) signal
onWorkerStop
void ServerConnection::onWorkerStop (ServerWorker * worker) protected slot
Definition at line 16 of file serverconnection.cpp.
Referenced by initServer().
{
   connections->removeAll(worker);
   delete worker;
 }
receiveResponce()
void ServerConnection::receiveResponce (DiffCard * diff, MessageForServer * message) virtual
Implements MailSender.
Definition at line 54 of file serverconnection.cpp.
                                                                   {}
run()
void ServerConnection::run () protected
Definition at line 27 of file serverconnection.cpp.
References ServerWorker::onSocketError().
{
   server = new QTcpServer();
   if (!server->listen(QHostAddress::Any, DefaultServerParams::port)) {
     emit onServerError(serverError::canNotStartServer);
     return;
   }
   qDebug() << server->isListening();
   bool isAppareNewConnection;
   while (true) {
     isAppareNewConnection = server->waitForNewConnection(-1);
     //    isAppareNewConnection = server->hasPendingConnections();
     if (isAppareNewConnection) {
       QTcpSocket* newConnection = server->nextPendingConnection();
       if (newConnection == nullptr)
         continue;
       qInfo() << "appare new connection  :: "
               << newConnection->peerAddress().toString() << ":"
               << newConnection->peerPort();
       ServerWorker* newWorker = new ServerWorker(newConnection);
       newWorker->setDefaultReceiver(this->receiver);
       connections->append(newWorker);
       newWorker->start();
     }
     msleep(30);
   }
 }
setDefaultReceiver()
virtual void MailSender::setDefaultReceiver (MailReceiver * receiver) inline virtual inherited
Definition at line 58 of file mailboxelement.h.
References MailSender::receiver.
{
     this->receiver = receiver;
   }
startServer()
void ServerConnection::startServer ()
Definition at line 21 of file serverconnection.cpp.
Referenced by initServer().
{
   if (this->isRunning())
     return;
   this->start(Priority::NormalPriority);
 }
Member Data Documentation
connections
QList<ServerWorker*>* ServerConnection::connections protected
Definition at line 32 of file serverconnection.h.
instance
ServerConnection * ServerConnection::instance = nullptr static protected
Definition at line 29 of file serverconnection.h.
Referenced by getServerInstance().
receiver
MailReceiver* MailSender::receiver protected inherited
Definition at line 63 of file mailboxelement.h.
Referenced by MailSender::setDefaultReceiver().
server
QTcpServer* ServerConnection::server protected
Definition at line 31 of file serverconnection.h.